name = 'snakesay'
desc = 'A less feature rewrite of cowsay in Python.'
version = '1.0.0'
version_type = 'development'
license = "GPL-3"
archs = ['universal'] # Possible values: 'arm64', 'x86_64', 'universal'
linux_archs = ['any'] # Possible values: 'any', 'x86_64'
types = ['build'] # Possible values: 'binary', 'build', 'app'
dependencies = []

[build]
repo = 'https://codeberg.org/zortazert/snakesay.git' # git repo to install
make_sudo  = true
make = [[], ['install']] # run make and then make install 

[[build.uninstall.universal]]
# Uninstall scripts
scripts = [['sudo', 'rm', '/usr/local/bin/snakesay'], ['sudo', 'rm', '/usr/local/share/fortunes.txt']]

[[build.uninstall.linux_any]]
scripts = [['sudo', 'rm', '/usr/bin/snakesay'], ['sudo', 'rm', '/usr/share/fortunes.txt']]
post_scripts = [['echo', 'Bye bye tux! :(']] # custom commands to run