name = 'basedfetch'
desc = 'cool example made for toaster'
version = '1.0.0'
version_type = 'stable'
license = "MIT"
archs = ['universal']
linux_archs = ['any']
types = ['build']
dependencies = []

[build]
repo = 'https://github.com/wxllow/basedfetch' # git repo to install
format_scripts = true # formats scripts and make with things like {prefix}
scripts = [['make', 'prefix={prefix}', 'install']] # run make and then make install 