# Should probably eventually become an "app" type once they r supported

name = "mpv"
homepage = "https://mpv.io/"
desc = "Media player based on MPlayer and mplayer2"
version = "0.34.1"
version_type = "release"
license = ""
archs = ["universal"]
# linux_archs = ["any"]
types = ["binary"]
dependencies = []

[binary]
type='gz'

url = 'https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.34.1.tar.gz'
format_scripts = true
link_dirs = ['bin']

scripts = [
    ['ln', '-s', '{prefix}', '{prefix}/mpv.app'],
    ['ln', '-s', '{prefix}/mpv.app', '/Applications/mpv.app'],
    ['mkdir', 'bin'],
    ['ln', '-s', '{prefix}/Contents/macOS/mpv', './bin/mpv']
]

[binary.uninstall]
scripts = [
    ['rm', '-rf', '/Applications/mpv.app']
]