# Should probably eventually become an "app" type once they r supported

name = "mpv"
homepage = "https://mpv.io/"
desc = "Media player based on MPlayer and mplayer2"
version = "0.34.1"
version_type = "release"
license = ""
archs = ["universal"]
# linux_archs = ["any"]
types = ["build"]
dependencies = []

[build]
type='gz'

url = 'https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.34.1.tar.gz'
format_scripts = true
scripts = [
    ['mkdir', '{prefix}/mpv.app'],
    ['cp', '-r', './', '{prefix}/mpv.app'],
    ['ln', '-s', '{prefix}/mpv.app', '/Applications/mpv.app'],
    ['ln', '-s', '{prefix}/mpv.app/Contents/macOS/mpv', '{prefix}/bin/mpv']
]

[build.uninstall]
scripts = [
    ['rm', '-rf', '/Applications/mpv.app']
]