name = "pkg-config"
homepage = "https://pkgconfig.freedesktop.org/"
desc = ""
version = "0.29.2"
version_type = "release"
license = "GPL-2.0"
archs = ["universal"]
linux_archs = ["any"]
types = ["build"]
dependencies = []

[build]
url = "https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz"
type = 'gz'
format_scripts = true
scripts = [
    ['./configure', 
        '--disable-debug',
        '--prefix={prefix}',
        '--disable-host-tool',
        '--with-internal-glib'
    ],
    ['make'],
    ['make', 'install']
]