name = 'coolexample'
desc = 'cool example made for toaster'
version = '1.0.0'
version_type = 'development'
license = "MIT"
archs = ['universal']
linux_archs = ['any']
types = ['build']
dependencies = []

[build]
repo = 'https://github.com/wxllow/coolexample' # git repo to install
format_scripts = true # formats scripts and make with things like {prefix}
scripts = [['echo', '{prefix}']]
make = [[], ['prefix={prefix}', 'install']] # run make and then make install 