name = "ani-cli"
desc = "A cli to browse and watch anime (alone AND with friends). This tool scrapes the site gogoplay."
version = "2.2"
version_type = "release"
license = "GPL-3.0"
archs = ["universal"]
linux_archs = ["any"]
types = ["build"]
dependencies = ['mpv']

[build]
repo = "https://github.com/pystardust/ani-cli"
branch = "v2.2"
format_scripts = true
link_dirs = ['']
scripts = [['mv', 'ani-cli', '{prefix}/ani-cli'], ['chmod', '+x', '{prefix}/ani-cli']]

    [build.linux_any]
    post_script = [
        ['printf', '\033[1;33mMake sure you have installed mpv, see https://mpv.io/installation/ for more info!\n\033[0m']
    ]