name = "ani-cli"
desc = "A cli to browse and watch anime (alone AND with friends). This tool scrapes the site gogoplay."
version = "2.2"
version_type = "release"
license = "GPL-3.0"
archs = ["universal"]
linux_archs = ["any"]
types = ["build"]
dependencies = []

[build]
repo = "https://github.com/pystardust/ani-cli"
branch = "v2.2"
format_scripts = true
link_dirs = ['']
scripts = [['mv', 'ani-cli', '{prefix}/ani-cli'], ['chmod', '+x', '{prefix}/ani-cli']]
