name = 'go'
desc = 'Open source programming language to build simple/reliable/efficient software'
version = '1.16'
version_type = 'stable'
license = "BSD-3-Clause"
archs = ['arm64', 'x86_64'] # Possible values: 'arm64', 'x86_64', 'universal'
linux_archs = ['any', 'x86_64']
types = ['binary'] # Possible values: 'binary', 'build', 'app'

[binary]
type = 'gz'
link_dirs = ['bin']

    [[binary.arm64]]
    url = 'https://storage.googleapis.com/golang/go1.16.darwin-arm64.tar.gz'

    [[binary.x86_64]]
    url = 'https://storage.googleapis.com/golang/go1.16.darwin-amd64.tar.gz'
    
    [[binary.linux_any]]
    url = 'https://storage.googleapis.com/golang/go1.16.linux-arm64.tar.gz'

    [[binary.linux_x86_64]]
    url = 'https://storage.googleapis.com/golang/go1.16.linux-amd64.tar.gz'