[info]
name = 'go'
desc = 'An open source programming language that makes it easy to build simple, reliable, and efficient software.'
version = '1.18'
version_type = 'stable'
license = "BSD-3-Clause"
archs = ['arm64', 'x86_64'] # Possible values: 'arm64', 'x86_64', 'universal'
types = ['binary'] # Possible values: 'binary', 'build', 'app'
dependencies = []

[binary]
    [[binary.arm64]]
    files = ['https://storage.googleapis.com/golang/go1.18.darwin-arm64.tar.gz']
    bin_dirs = ['bin']
    [[binary.x86_64]]
    files = ['https://storage.googleapis.com/golang/go1.18.darwin-amd64.tar.gz']

    [[binary.install]] # Install options for all architectures
    pre_scripts = [['echo', "You're about to get go!"]] 
    post_scripts = [['echo', 'Thanks for downloading go!']]

        [[binary.install.arm64]]
        post_scripts = [['echo', "Using arm!"]]

        [[binary.install.x86_64]]
        post_scripts = [['echo', 'Using x86_84!']]

    [[binary.uninstall]]
    post_scripts = [['echo', 'No more go :(']]


