name = "Python"
homepage = "https://www.python.org/"
desc = "Python is a programming language that lets you work more quickly and integrate your systems more effectively."
version = "3.10.4"
version_type = "release"
license = "PSF"
archs = ["arm64", "x86_64"]
linux_archs = ["any"]
types = ["binary", "build"]
dependencies = []

[binary]
type = 'gz'

    [[ binary.arm64 ]]
    url = 'https://github.com/indygreg/python-build-standalone/releases/download/20220502/cpython-3.10.4+20220502-aarch64-apple-darwin-install_only.tar.gz'

    [[ binary.x86_64 ]]
    url = 'https://github.com/indygreg/python-build-standalone/releases/download/20220502/cpython-3.10.4+20220502-x86_64-apple-darwin-install_only.tar.gz'

    [[ binary.linux_any ]]
    url = 'https://github.com/indygreg/python-build-standalone/releases/download/20220502/cpython-3.10.4+20220502-aarch64-unknown-linux-gnu-install_only.tar.gz'

    [[ binary.linux_x86_64 ]]
    url = 'https://github.com/indygreg/python-build-standalone/releases/download/20220502/cpython-3.10.4+20220502-x86_64-unknown-linux-gnu-install_only.tar.gz'

[build]
repo = "https://github.com/python/cpython"
branch = "v3.10.4"
format_scripts = true
scripts = [
    ['./configure', '--prefix={prefix}', '--with-ssl', '--enable-optimizations', '--CFLAGS="-Wno-error=unused-command-line-argument"'], 
    ['make'], ['make', 'test', '||', 'exit', '1'], ['make', 'install']
]