name = "Python"
desc = "Python is a programming language that lets you work more quickly and integrate your systems more effectively."
version = "3.10.4"
version_type = "release"
license = "PSF"
archs = ["universal"]
linux_archs = ["any"]
types = ["build"]
dependencies = []

[build]
repo = "https://github.com/python/cpython"
branch = "v3.10.4"
format_scripts = true
scripts = [
    ['./configure', '--prefix={prefix}', '--with-ssl', '--enable-optimizations', '--CFLAGS="-Wno-error=unused-command-line-argument"'], 
    ['make'], ['make', 'test', '||', 'exit', '1'], ['make', 'install']
]