name = "Python"
desc = "Python is a programming language that lets you work more quickly and integrate your systems more effectively."
version = "3.10.4"
version_type = "release"
license = "PSF"
archs = ["universal"]
linux_archs = ["any"]
types = ["build"]
dependencies = []

[build]
repo = "https://github.com/python/cpython"
branch = "v3.10.4"
format_scripts = true
scripts = [
    ['./configure', '--prefix={prefix}', '--with-ssl', '--enable-optimizations'], 
    ['make'], ['make', 'test', '||', 'exit', '1'], ['make', 'install']
]
post_scritps = [[
        'curl', 
        'https://raw.githubusercontent.com/pypa/cibuildwheel/main/cibuildwheel/resources/install_certifi.py', 
        '--output', 
        'install_certifi.py',
        '&&',
        'bin/python3',
        './install_certifi.py'
    ], 
    [
        'bin/python3',
        '-m',
        'pip',
        'install',
        'GitPython',
        'atomicwrites',
        'click',
        'click-aliases',
        'filelock',
        'packaging',
        'requests',
        'toml',
        'tqdm',
        'validators',
    ]
]